name: Build my QMK configuration

on:
  workflow_dispatch:

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd
          keymap: default

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: qmk-firmware-to-be-flashed
